### ISSUE TITLE
NOT AN ISSUE: Thanks Instead

### ISSUE THREAD

**Issue by Tribalwarfare** [MVogwell/ps_Azure_ParseNsgFlowLog#1]
Hi Thank you for posting your conversion script.
It was really useful when I needed to get a quick flow log dump analysed :)

PS: Also works fine with Powershell 7.1 for Linux (Debian 12)

Kind Regards,
AG

**Comment by MVogwell** [comment]
AG,

Thanks for letting me know, glad it could help! 

All the best, 

Martin
